### PR TITLE
add timezone in token

### PR DESCRIPTION
**Pull request by jonascheng**
need to upgrade in thor if @matrix0415 you would like to create test case base on timezone.

### CODE REVIEW

**Comment by jonascheng** [comment]
Local pytest 也遇到相同錯誤
ImportError while importing test module '/home/travis/build/drmobile/services-lib/tests/test_flask_soocii_auth.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_flask_soocii_auth.py:7: in <module>
    from flask.ext.soocii_auth import SoociiAuthenticator
E   ImportError: No module named 'flask.ext'

是不是遺漏了什麼步驟？

**Comment by calvin620707** [comment]
好像印象flask打算deprecated flask.ext 的方式去import extension ，不知道會不會是因為這個

**Comment by calvin620707** [comment]
@jonascheng  try `from flask_soocii_auth import SoociiAuthenticator`

**Comment by calvin620707** [comment]
https://github.com/pallets/flask/issues/1135

**Pull request merged**
